### ISSUE TITLE
兄弟, 升级到2.1报错了

### ISSUE THREAD

**Issue by CNDrwei** [nick-zh/docker-kafka-eagle#6] opened 2022-02-10 09:32 UTC
![image](https://user-images.githubusercontent.com/40556785/153378465-dfc4a496-4059-4398-90c6-69a271491208.png)

**Comment by nick-zh** [comment] 2022-02-10 11:32
Many thanks for the report :pray: 
I tried to do the following:
- create the db dir
- create the db dir & touch the db file

Both things did not get rid of the error. I don't think there is much more i can do.
After starting the container, i can see that the db file is properly populated, so maybe the error can be ignored :man_shrugging: 
I will try to check the EFAK code, to see if i can get more information though.

**Comment by nick-zh** [comment] 2022-02-10 11:59
I found the root cause and reported it [here](https://github.com/smartloli/EFAK/issues/586) :v:
I will close this issue, since it is a problem in the main project.
Thx again for pointing it out :v:

**Closed by nick-zh** 2022-02-10 11:59 UTC
